// Новые материалы дополняют data.js. Старые идентификаторы 1–8 и 1–12 не меняются.
Object.assign(COURSES, {
  daily: { title: 'Python в повседневных задачах', testTitle: 'Python в повседневных задачах', count: 4, minutes: 40, description: 'Покупки, работа с текстом и небольшая игра — применяем знакомый Python.', symbol: 'Py+', icon: 'code', tags: ['Python', 'Применяем основы'] },
  design: { title: 'Создаём красивую веб-страницу', testTitle: 'Красивая веб-страница', count: 4, minutes: 40, description: 'Карточки, Flexbox и адаптивность. Собираем аккуратную страницу по образцу.', symbol: 'CSS', icon: 'code', tags: ['HTML / CSS', 'Вёрстка'] },
  javascript: { title: 'Первые шаги в JavaScript', testTitle: 'Первые шаги в JavaScript', count: 4, minutes: 40, description: 'Добавляем страницам поведение: кнопки, изменение текста и счётчик.', symbol: 'JS', icon: 'code', tags: ['JavaScript', 'Интерактивность'] }
});
const NEW_COURSES = ['daily', 'design', 'javascript'];
LESSONS.push(
  { id:9,course:'daily',title:'Покупки, скидки и среднее',subtitle:'Превращаем арифметику в полезные расчёты.',minutes:10,
    text:'Разделяй задачу на данные и вычисления. Стоимость равна цене, умноженной на количество. Скидка 20% оставляет 80% цены. Среднее — сумма значений, делённая на их количество. Скобки задают порядок действий. Для простых учебных расчётов используем числа и round().',
    examples:[['price = 250\nquantity = 3\ntotal = price * quantity\nwith_discount = total * (1 - 20 / 100)\nprint(round(with_discount, 2))','Получим 600.0: три покупки по 250 со скидкой 20%. round(x, 2) округляет до двух знаков.'],['scores = [4, 5, 3]\naverage = sum(scores) / len(scores)\nprint(average)','Среднее равно 4.0. sum() складывает числа, len() считает их. Здесь список не пустой: на ноль делить нельзя.']],
    check:{question:'Сколько стоит покупка за 200 после скидки 10%?',answers:['180','180.0'],hint:'Вычти 20 из 200.',explanation:'10% от 200 — это 20. Цена после скидки: 180.'}},
  { id:10,course:'daily',title:'Работа со строками',subtitle:'Ищем, заменяем и форматируем текст.',minutes:10,
    text:'Строковые методы создают новый текст, не изменяя исходную строку. lower() приводит буквы к нижнему регистру, strip() удаляет пробелы по краям, replace() заменяет фрагмент. Оператор in проверяет наличие подстроки. f-строка подставляет значения переменных в фигурные скобки.',
    examples:[['text = "  Учим Python  "\nclean = text.strip().lower()\nprint("python" in clean)\nprint(clean.replace("python", "код"))','Получим True и учим код. Для поиска без учёта регистра сначала приводим текст к одному регистру.'],['name = "Аня"\npoints = 12\nprint(f"{name}: {points} баллов")','Результат: Аня: 12 баллов. Буква f стоит перед открывающей кавычкой.']],
    check:{question:'Что вернёт "кот".replace("к", "р")?',answers:['рот'],hint:'Заменяется только буква к.',explanation:'replace() заменит к на р: получится рот.'}},
  { id:11,course:'daily',title:'Список дел',subtitle:'Добавление, удаление и обработка элементов.',minutes:10,
    text:'append() добавляет элемент, remove() удаляет первое совпадение по значению, pop() удаляет и возвращает элемент по индексу (без индекса — последний). Проверяй наличие элемента перед remove(). Когда нужно отобрать элементы, проще создавать новый список, чем удалять элементы из списка во время перебора.',
    examples:[['tasks = ["уроки", "прогулка"]\ntasks.append("чтение")\nif "уроки" in tasks:\n    tasks.remove("уроки")\nprint(tasks)','Получим [\'прогулка\', \'чтение\']. Проверка in предотвращает удаление отсутствующего значения.'],['numbers = [2, 7, 4, 9]\nlarge = []\nfor number in numbers:\n    if number > 5:\n        large.append(number)\nprint(large)','Новый список содержит [7, 9]. Исходный список не меняется.']],
    check:{question:'Какой метод удалит первое совпадение по значению?',options:['append()','remove()','lower()','len()'],answers:['remove()'],hint:'Нужен метод удаления, а не добавления.',explanation:'remove(value) удаляет первый элемент с таким значением.'}},
  { id:12,course:'daily',title:'Случайные числа и игра',subtitle:'Делаем короткую игру «Угадай число».',minutes:10,
    text:'Модуль random входит в Python. randint(a, b) выбирает целое число от a до b включительно. Сначала импортируем модуль, затем генерируем секрет один раз до цикла. input() принимает догадку. Для учебного примера вводи целые числа; обработку неправильного ввода пока не добавляем.',
    examples:[['import random\ndice = random.randint(1, 6)\nprint(dice)','Это бросок кубика: возможны 1, 2, 3, 4, 5 и 6. Результат может повторяться.'],['import random\nsecret = random.randint(1, 10)\nguess = 0\nwhile guess != secret:\n    guess = int(input("Число от 1 до 10: "))\n    if guess < secret:\n        print("Нужно больше")\n    elif guess > secret:\n        print("Нужно меньше")\nprint("Угадано!")','Секрет не меняется между попытками. При совпадении цикл завершится. Вводи только целое число.']],
    check:{question:'Может ли random.randint(1, 6) вернуть 6?',options:['Да','Нет','Только 0','Только 7'],answers:['Да'],hint:'Обе границы randint() включены.',explanation:'В отличие от range(), randint() включает правую границу.'}},
  { id:13,course:'design',title:'Карточки и кнопки',subtitle:'Собираем повторяемые элементы страницы.',minutes:10,
    text:'Карточка объединяет связанные заголовок, текст и действие. Используй один класс для одинаковых карточек. box-sizing: border-box включает рамку и padding в заданную ширину. Ссылка подходит для перехода, button — для действия. Оставляй заметный фокус для клавиатуры.',
    examples:[['<article class="card">\n  <h2>Мой проект</h2>\n  <p>Короткое описание.</p>\n  <a class="button" href="./project.html">Открыть</a>\n</article>','Одна карточка — один смысловой блок. Файл project.html должен существовать рядом.'],['* { box-sizing: border-box; }\n.card { padding: 24px; border: 1px solid #ddd; border-radius: 12px; }\n.button { display: inline-block; padding: 12px 18px; background: #4b5ee8; color: white; }\n.button:focus-visible { outline: 3px solid #b58900; outline-offset: 3px; }','Padding создаёт пространство внутри. Рамка и скругление отделяют карточку от фона. Контур отмечает фокус.']],
    check:{question:'Что включает padding в заданную ширину элемента?',options:['box-sizing: border-box','color: blue','font-size: 16px','text-align: center'],answers:['box-sizing: border-box'],hint:'Ищи свойство модели размеров.',explanation:'border-box считает padding и рамку частью width.'}},
  { id:14,course:'design',title:'Расположение с Flexbox',subtitle:'Выравниваем элементы и разрешаем перенос.',minutes:10,
    text:'display: flex превращает родителя во flex-контейнер. По умолчанию элементы идут в строку. gap задаёт промежутки, justify-content выравнивает вдоль главной оси, align-items — вдоль поперечной. flex-wrap: wrap разрешает перенос, если места не хватает.',
    examples:[['.toolbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 16px;\n}','Два элемента панели разойдутся к краям строки, оставаясь выровненными по высоте.'],['.cards { display: flex; flex-wrap: wrap; gap: 16px; }\n.card { flex: 1 1 220px; }','Карточки имеют желаемую основу 220px, могут растягиваться и переноситься. Flexbox применяется к непосредственным детям контейнера.']],
    check:{question:'Как разрешить перенос элементов Flexbox?',answers:['flex-wrap: wrap','flex-wrap: wrap;'],hint:'Название свойства начинается с flex-wrap.',explanation:'flex-wrap: wrap разрешает дополнительную строку.'}},
  { id:15,course:'design',title:'Страница на телефоне',subtitle:'Адаптируем ширину, изображения и расположение.',minutes:10,
    text:'Адаптивная страница подстраивается под экран. В head нужен meta viewport. Избегай больших фиксированных ширин: используй width: 100% и max-width. Медиаусловие меняет стили при заданной ширине. Проверяй страницу от 320px и не скрывай проблему обрезанием всей страницы.',
    examples:[['<meta name="viewport" content="width=device-width, initial-scale=1">\n<style>\n  img { max-width: 100%; height: auto; }\n  .page { width: 100%; max-width: 960px; margin: auto; padding: 16px; box-sizing: border-box; }\n</style>','Картинка не шире контейнера, а страница сохраняет внутренние отступы.'],['.cards { display: flex; gap: 16px; }\n@media (max-width: 600px) {\n  .cards { flex-direction: column; }\n}','На узком экране карточки расположатся друг под другом. Браузер выбирает правило по ширине окна.']],
    check:{question:'Какое условие действует при ширине 320px?',options:['@media (min-width: 900px)','@media (max-width: 600px)','@media (min-width: 700px)','@media (min-width: 1200px)'],answers:['@media (max-width: 600px)'],hint:'320 меньше 600.',explanation:'max-width означает «не шире указанного значения».'}},
  { id:16,course:'design',title:'Страница по образцу',subtitle:'Соединяем карточки, отступы и адаптивность.',minutes:10,
    text:'Образец: светлый фон, заголовок «Мои увлечения», две белые карточки с отступом 16px между ними и синие ссылки. На телефоне карточки стоят в столбик. Сначала опиши блоки в HTML, затем их расположение и внешний вид в CSS. Сравни результат с этим описанием по одному пункту.',
    examples:[['<h1>Мои увлечения</h1>\n<div class="cards">\n  <article class="card"><h2>Код</h2><p>Делаю сайты.</p><a href="#plan">Мой план</a></article>\n  <article class="card"><h2>Музыка</h2><p>Учусь играть.</p><a href="#plan">Мой план</a></article>\n</div>\n<h2 id="plan">Мой план</h2>\n<p>Практиковаться каждый день.</p>','Ссылки ведут к существующему заголовку plan. Для просмотра положи фрагмент в body полноценной HTML-страницы.'],['body { background: #f5f7ff; font-family: Arial, sans-serif; padding: 20px; }\n.cards { display: flex; flex-wrap: wrap; gap: 16px; }\n.card { flex: 1 1 220px; background: white; padding: 20px; border-radius: 12px; }\na { color: #3548cc; }\n@media (max-width: 600px) { .cards { flex-direction: column; } }','Проверь белые карточки, синие ссылки и перенос. Дополнительное задание: измени цвет фона, сохранив читаемость.']],
    check:{question:'Какое свойство задаёт промежуток между карточками во Flexbox?',answers:['gap'],hint:'Название состоит из трёх букв.',explanation:'gap задаёт расстояние между элементами контейнера.'}},
  { id:17,course:'javascript',title:'Переменные JavaScript',subtitle:'Первые вычисления прямо в браузере.',minutes:10,
    text:'JavaScript добавляет поведение веб-странице. Примеры этого урока можно вводить в консоль инструментов разработчика браузера. let создаёт переменную, значение которой можно менять; const — переменную, которой нельзя присвоить другое значение. console.log() выводит данные в консоль. Числа пишутся без кавычек.',
    examples:[['let points = 5;\npoints = points + 2;\nconsole.log(points);','В консоли появится 7. В JavaScript для объявления переменной используется let или const.'],['const price = 100;\nconst count = 3;\nconsole.log(price * count);\nconsole.log("100" + "3");','Первый результат — число 300, второй — строка 1003. Плюс у строк соединяет текст.']],
    check:{question:'Какое слово позволяет позже присвоить переменной другое значение?',options:['const','let','print','def'],answers:['let'],hint:'const не допускает повторного присваивания.',explanation:'let подходит для счётчиков и других изменяемых значений.'}},
  { id:18,course:'javascript',title:'Нажатия кнопок',subtitle:'Находим элемент и подключаем обработчик.',minutes:10,
    text:'document.querySelector() находит первый элемент по CSS-селектору. addEventListener() связывает событие с функцией. Для кнопки подходит событие click. Подключай скрипт после HTML кнопки или используй defer, чтобы элемент уже существовал. Функция-обработчик выполняется после нажатия.',
    examples:[['<button id="hello">Поздороваться</button>\n<p id="message"></p>\n<script src="./script.js" defer></script>','Сохрани в HTML, а следующий пример — в script.js рядом с ним.'],['const button = document.querySelector("#hello");\nbutton.addEventListener("click", () => {\n  document.querySelector("#message").textContent = "Привет!";\n});','После щелчка или активации кнопки клавиатурой абзац изменится. #hello выбирает элемент по id.']],
    check:{question:'Какое событие нужно для нажатия кнопки?',answers:['click'],hint:'Название совпадает с английским словом «щелчок».',explanation:'click вызывается при активации кнопки.'}},
  { id:19,course:'javascript',title:'Меняем текст и классы',subtitle:'Отделяем поведение страницы от оформления.',minutes:10,
    text:'textContent меняет текст элемента и не превращает его в HTML. classList.add() добавляет CSS-класс, remove() убирает, toggle() переключает. Пусть CSS отвечает за цвет и оформление, а JavaScript — за изменение состояния.',
    examples:[['<p id="status">Не готово</p>\n<style>.done { color: #167353; font-weight: bold; }</style>\n<script>\n  const status = document.querySelector("#status");\n  status.textContent = "Готово!";\n  status.classList.add("done");\n</script>','Абзац сразу станет зелёным с текстом Готово! Скрипт расположен после элемента.'],['const button = document.querySelector("#hello");\nbutton.addEventListener("click", () => {\n  button.classList.toggle("selected");\n});','Для кнопки #hello из прошлого урока класс selected будет добавляться и убираться. Чтобы видеть разницу, опиши .selected в CSS.']],
    check:{question:'Какое свойство безопасно задаёт обычный текст?',options:['textContent','innerHTML','font-size','href'],answers:['textContent'],hint:'В названии есть слово text.',explanation:'textContent отображает строку как текст, не исполняя разметку.'}},
  { id:20,course:'javascript',title:'Интерактивный счётчик',subtitle:'Храним число и обновляем его на странице.',minutes:10,
    text:'Храни значение счётчика в переменной, а на страницу выводи его через одну функцию обновления. По нажатию увеличивай число, по сбросу присваивай ноль. В этом учебном примере после обновления страницы счётчик начинается заново.',
    examples:[['<p>Нажатий: <span id="count">0</span></p>\n<button id="plus">+1</button>\n<button id="reset">Сбросить</button>\n<script src="./counter.js" defer></script>','Создай рядом counter.js со следующим кодом. У кнопок разные id.'],['let count = 0;\nconst output = document.querySelector("#count");\nfunction update() { output.textContent = count; }\ndocument.querySelector("#plus").addEventListener("click", () => {\n  count += 1;\n  update();\n});\ndocument.querySelector("#reset").addEventListener("click", () => {\n  count = 0;\n  update();\n});','+= 1 увеличивает значение на единицу. Переменная count объявлена снаружи обработчика и не обнуляется при каждом нажатии.']],
    check:{question:'Счётчик был 0. После трёх нажатий +1 и одного сброса он равен…',answers:['0'],hint:'Последнее действие присваивает ноль.',explanation:'Сброс устанавливает count = 0 независимо от предыдущего значения.'}}
);
TASKS.push(
  {id:13,course:'daily',title:'Скидка',question:'Что выведет программа?',code:'print(500 * 0.8)',answers:['400.0'],hint:'После скидки остаётся 80%. Результат умножения на float тоже float.',explanation:'500 × 0.8 = 400.0: скидка 20%.'},
  {id:14,course:'daily',title:'Средний балл',question:'Заполни пропуск.',code:'marks = [3, 4, 5]\naverage = sum(marks) / ___(marks)',answers:['len'],hint:'Нужно количество оценок.',explanation:'len(marks) возвращает 3, среднее равно 4.0.'},
  {id:15,course:'daily',title:'Поиск без регистра',question:'Как найти слово python независимо от регистра букв в text?',options:['"python" in text.lower()','text + "python"','text.remove("python")','len(text) == "python"'],answers:['"python" in text.lower()'],hint:'Приведи строку к нижнему регистру.',explanation:'lower() делает регистр одинаковым, in проверяет наличие подстроки.'},
  {id:16,course:'daily',title:'Удаление дела',question:'Исправь ошибку: tasks.remove("спорт") падает, если такого дела нет.',options:['Сначала проверить if "спорт" in tasks','Заменить на tasks + 1','Убрать кавычки','Вызвать int(tasks)'],answers:['Сначала проверить if "спорт" in tasks'],hint:'Перед удалением проверь наличие.',explanation:'remove() требует существующего значения, проверка in делает удаление безопасным.'},
  {id:17,course:'daily',title:'Последний элемент',question:'Что выведет программа?',code:'items = [2, 4, 6]\nlast = items.pop()\nprint(last)',answers:['6'],hint:'Без индекса pop() берёт последний элемент.',explanation:'pop() удалит 6 и вернёт его в last.'},
  {id:18,course:'daily',title:'Не меняем секрет',question:'Где генерировать секрет для игры «Угадай число»?',options:['Один раз перед циклом','Внутри цикла на каждой попытке','После каждой подсказки','Только после победы'],answers:['Один раз перед циклом'],hint:'Одно загаданное число должно оставаться тем же.',explanation:'Генерация перед циклом сохраняет секрет на всю игру.'},
  {id:19,course:'design',title:'Скругление',question:'Какое свойство скругляет углы карточки?',answers:['border-radius'],hint:'Свойство относится к рамке.',explanation:'border-radius задаёт радиус скругления.'},
  {id:20,course:'design',title:'Расстояния',question:'Как задать 16px между элементами Flexbox?',options:['gap: 16px','color: 16px','font-family: 16px','display: 16px'],answers:['gap: 16px'],hint:'Нужно свойство промежутка.',explanation:'gap: 16px создаёт промежуток между соседними элементами.'},
  {id:21,course:'design',title:'На узком экране',question:'Какое направление расположит карточки в столбик?',options:['flex-direction: row','flex-direction: column','justify-content: center','color: blue'],answers:['flex-direction: column'],hint:'Столбец по-английски — column.',explanation:'column меняет главную ось на вертикальную.'},
  {id:22,course:'design',title:'Слишком широкая картинка',question:'Выбери исправление картинки, которая вылезает за экран.',options:['max-width: 100%; height: auto','width: 2000px','font-size: 100px','margin: 1000px'],answers:['max-width: 100%; height: auto'],hint:'Ограничь ширину размером родителя.',explanation:'max-width ограничивает ширину, height: auto сохраняет пропорции.'},
  {id:23,course:'design',title:'Что увидим?',question:'Экран имеет ширину 400px. Как расположатся карточки?',code:'.cards { display: flex; }\n@media (max-width: 600px) {\n  .cards { flex-direction: column; }\n}',options:['В столбик','Всегда в строку','Исчезнут','CSS не применится'],answers:['В столбик'],hint:'400 меньше 600.',explanation:'Медиаусловие истинно, поэтому применяется column.'},
  {id:24,course:'design',title:'Включаем Flexbox',question:'Заполни пропуск: display: ___;',answers:['flex'],hint:'Название технологии без слова box.',explanation:'display: flex включает flex-контейнер.'},
  {id:25,course:'javascript',title:'Числа и текст',question:'Что выведет console.log("2" + "3")?',answers:['23'],hint:'Оба значения — строки.',explanation:'Оператор + соединяет строки, а не складывает числа.'},
  {id:26,course:'javascript',title:'Изменяемая переменная',question:'Исправь const count = 0; count += 1;',options:['Заменить const на let','Заменить 0 на "0"','Добавить print()','Заменить += на =='],answers:['Заменить const на let'],hint:'Счётчику нужно присваивать новое значение.',explanation:'Повторное присваивание const запрещено; для счётчика нужен let.'},
  {id:27,course:'javascript',title:'Событие',question:'Заполни пропуск.',code:'button.addEventListener("___", () => {\n  console.log("Нажато");\n});',answers:['click'],hint:'Событие активации кнопки.',explanation:'click работает при нажатии мышью и активации кнопки клавиатурой.'},
  {id:28,course:'javascript',title:'Переключаем выделение',question:'Как переключить класс active?',options:['element.classList.toggle("active")','element.textContent("active")','element.style = click','print("active")'],answers:['element.classList.toggle("active")'],hint:'Нужен метод переключения.',explanation:'toggle() добавляет отсутствующий класс и убирает существующий.'},
  {id:29,course:'javascript',title:'Считаем нажатия',question:'Чему равно count?',code:'let count = 1;\ncount += 1;\ncount += 1;',answers:['3'],hint:'Два раза прибавляем единицу к 1.',explanation:'1 + 1 + 1 = 3.'},
  {id:30,course:'javascript',title:'Элемент ещё не создан',question:'Скрипт в head не находит кнопку ниже. Выбери исправление подключения.',options:['Добавить defer к внешнему script','Удалить кнопку','Поменять цвет кнопки','Использовать input()'],answers:['Добавить defer к внешнему script'],hint:'Выполнение нужно отложить до разбора HTML.',explanation:'defer у внешнего скрипта откладывает выполнение до готовности HTML-структуры.'}
);
Object.assign(TESTS, {
  daily:[
    ['Как найти среднее чисел непустого списка a?',['sum(a) / len(a)','sum(a) * len(a)','len(a) / sum(a)','a + 2'],0,'Среднее — сумма, делённая на количество.'],
    ['Что делает strip()?',['Удаляет все буквы','Удаляет пробелы по краям','Меняет числа на строки','Сортирует список'],1,'strip() убирает пробельные символы по краям строки.'],
    ['Что делает items.append(5)?',['Удаляет 5','Заменяет весь список','Добавляет 5 в конец','Возвращает длину'],2,'append() добавляет один элемент в конец.'],
    ['Какие значения возможны у randint(2, 4)?',['Только 2','2 и 3','3 и 4','2, 3 и 4'],3,'Обе границы включены.'],
    ['Как вставить name в строку?',['f"Привет, {name}"','"Привет, name"','name(Привет)','print = name'],0,'f-строка подставляет значения внутри фигурных скобок.']
  ],
  design:[
    ['Что включает padding в width?',['display: flex','box-sizing: border-box','color: red','margin: auto'],1,'border-box включает padding и рамку в заданный размер.'],
    ['Чем включают Flexbox?',['position: fixed','font-weight: bold','display: flex','display: none'],2,'Flexbox включается у родителя через display: flex.'],
    ['Как разрешить перенос элементов?',['flex-wrap: wrap','flex-wrap: none','color: wrap','gap: auto'],0,'wrap разрешает несколько строк.'],
    ['Какое правило применится при 500px?',['@media (min-width: 800px)','@media (min-width: 1000px)','@media (min-width: 600px)','@media (max-width: 600px)'],3,'500px не превышает 600px.'],
    ['Зачем нужен :focus-visible?',['Для удаления текста','Для видимого фокуса клавиатуры','Для загрузки картинки','Для запуска Python'],1,'Контур фокуса показывает, какой элемент будет активирован.']
  ],
  javascript:[
    ['Что выбрать для изменяемого счётчика?',['const','def','let','int'],2,'let допускает повторное присваивание.'],
    ['Что выведет console.log(2 + 3)?',['23','5','2 + 3','undefined'],1,'Без кавычек складываются числа.'],
    ['Как выбрать элемент с id="count"?',['document.querySelector("#count")','document.querySelector(".count")','print(count)','input(count)'],0,'Селектор id начинается с #.'],
    ['Что меняет обычный текст элемента?',['innerWidth','href','className()','textContent'],3,'textContent задаёт текст без интерпретации HTML.'],
    ['Почему count нужно объявить вне обработчика кнопки?',['Чтобы запретить клики','Чтобы число сохранялось между нажатиями','Чтобы скрыть кнопку','Чтобы подключить CSS'],1,'Объявление внутри обработчика заново создавало бы переменную при каждом клике.']
  ]
});

const PROJECTS = [
  {id:'calculator',title:'Калькулятор на Python',course:'daily',goal:'Ввести два числа и действие, получить результат. Деление на ноль должно выводить понятное сообщение.',where:'Установи Python 3, открой IDLE, создай файл calculator.py, вставь код и выбери Run → Run Module (F5). Вводи числа с точкой; в учебном варианте обработка произвольного текста не предусмотрена.',
    steps:[['Получаем данные','Запроси два числа через float(input(...)) и действие через input().','a = float(input("Первое число: "))\nb = float(input("Второе число: "))\nop = input("Действие (+, -, *, /): ")'],['Выбираем операцию','Используй if / elif для четырёх действий. Не забудь двоеточия и отступы.','if op == "+":\n    print(a + b)'],['Проверяем деление','Перед a / b проверь, не равен ли b нулю. В последнем else обработай неизвестную операцию.','if b == 0:\n    print("На ноль делить нельзя")\nelse:\n    print(a / b)']],
    checklist:['2 + 3 даёт 5.0','7 - 2 даёт 5.0, 3 * 4 даёт 12.0','8 / 2 даёт 4.0','При делении на 0 есть сообщение','Для неизвестной операции есть сообщение'],
    solution:'a = float(input("Первое число: "))\nb = float(input("Второе число: "))\nop = input("Действие (+, -, *, /): ")\nif op == "+":\n    print(a + b)\nelif op == "-":\n    print(a - b)\nelif op == "*":\n    print(a * b)\nelif op == "/":\n    if b == 0:\n        print("На ноль делить нельзя")\n    else:\n        print(a / b)\nelse:\n    print("Неизвестное действие")'},
  {id:'personal-page',title:'Личная страница на HTML и CSS',course:'design',goal:'Собрать страницу о своих увлечениях: заголовок, две карточки и работающая ссылка внутри страницы. На телефоне карточки — в столбик.',where:'Создай папку проекта и файл index.html в обычном текстовом редакторе. Сохрани в UTF-8 с расширением .html, а не .txt. Открой файл браузером; после изменения обновляй страницу.',
    steps:[['Создаём документ','Добавь doctype, html lang="ru", head с кодировкой и viewport, затем body.','<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">'],['Добавляем содержание','В body добавь заголовок, две карточки увлечений и ссылку на свой раздел «План».','<h1>Мои увлечения</h1>\n<a href="#plan">К плану</a>'],['Оформляем и проверяем телефон','Размести правила в style внутри head. Используй flex-wrap и медиаправило.','.cards { display: flex; flex-wrap: wrap; gap: 16px; }']],
    checklist:['Есть главный заголовок и два увлечения','Ссылка переводит к разделу «План»','Карточки отделены от фона','При 320px нет общей горизонтальной прокрутки','Клавиша Tab выделяет ссылку'],
    solution:'<!doctype html>\n<html lang="ru">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>Моя страница</title>\n<style>\n* { box-sizing: border-box; }\nbody { margin: 0; padding: 20px; font: 16px/1.6 Arial, sans-serif; background: #f5f7ff; color: #202738; }\nmain { max-width: 900px; margin: auto; }\n.cards { display: flex; flex-wrap: wrap; gap: 16px; }\n.card { flex: 1 1 220px; background: white; padding: 20px; border-radius: 12px; }\na { color: #3548cc; }\na:focus-visible { outline: 3px solid #b58900; outline-offset: 4px; }\n@media (max-width: 600px) { .cards { flex-direction: column; } }\n</style>\n</head>\n<body><main>\n<h1>Мои увлечения</h1>\n<p>Здесь я рассказываю о том, что мне интересно.</p>\n<div class="cards">\n<article class="card"><h2>Программирование</h2><p>Создаю первые проекты.</p><a href="#plan">Мой план</a></article>\n<article class="card"><h2>Музыка</h2><p>Учусь играть любимые мелодии.</p><a href="#plan">Мой план</a></article>\n</div>\n<h2 id="plan">План</h2><p>Каждый день пробовать что-то новое.</p>\n</main></body></html>'},
  {id:'click-counter',title:'Счётчик нажатий на JavaScript',course:'javascript',goal:'Кнопка +1 увеличивает число, кнопка «Сбросить» возвращает ноль. Обновляется текст, а не вся страница.',where:'Создай index.html в текстовом редакторе, вставь готовое решение или собирай его по шагам. Открой в браузере. JavaScript здесь размещается в script в конце body.',
    steps:[['Делаем интерфейс','Добавь число и две кнопки с разными id.','<p>Нажатий: <span id="count">0</span></p>\n<button id="plus">+1</button>\n<button id="reset">Сбросить</button>'],['Храним состояние','Объяви count один раз. Создай функцию вывода значения.','let count = 0;\nconst output = document.querySelector("#count");\nfunction update() { output.textContent = count; }'],['Подключаем действия','Добавь обработчики click для обеих кнопок. После изменения переменной вызывай update().','document.querySelector("#plus").addEventListener("click", () => { count += 1; update(); });']],
    checklist:['Изначально показан 0','После трёх нажатий показан 3','Сброс возвращает 0','Кнопки доступны с клавиатуры','После обновления страницы показан 0 — это ожидаемо'],
    solution:'<!doctype html>\n<html lang="ru"><head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>Счётчик</title>\n<style>body { font: 18px Arial, sans-serif; padding: 24px; } button { padding: 12px 18px; margin: 4px; } button:focus-visible { outline: 3px solid #4b5ee8; }</style>\n</head><body>\n<h1>Счётчик нажатий</h1>\n<p aria-live="polite">Нажатий: <span id="count">0</span></p>\n<button id="plus">+1</button><button id="reset">Сбросить</button>\n<script>\nlet count = 0;\nconst output = document.querySelector("#count");\nfunction update() { output.textContent = count; }\ndocument.querySelector("#plus").addEventListener("click", () => { count += 1; update(); });\ndocument.querySelector("#reset").addEventListener("click", () => { count = 0; update(); });\n</script></body></html>'}
];
const REFERENCE = [
  ['Python','print()','вывод печать экран','print("Привет")','Выводит текст или значения на экран.'],
  ['Python','input() и int()','ввод число преобразование','age = int(input("Возраст: "))','input() возвращает строку. int() превращает корректную запись целого числа в число.'],
  ['Python','if / elif / else','условие сравнение ветвление','if score >= 70:\n    print("Сдано")\nelse:\n    print("Повтори")','Выполняется подходящая ветка. Для равенства используй ==.'],
  ['Python','for и range()','цикл повторение перебор','for i in range(3):\n    print(i)','Будут выведены 0, 1, 2. Правая граница не включается.'],
  ['Python','while','цикл условие повторение','n = 3\nwhile n > 0:\n    print(n)\n    n -= 1','Повторяет блок, пока условие истинно. Не забудь менять условие выхода.'],
  ['Python','Списки','append remove pop len индекс','items = ["код", "музыка"]\nitems.append("книга")\nprint(items[0])','Индексы начинаются с 0. append добавляет, remove удаляет по значению, pop — по индексу.'],
  ['Python','Функции','def return параметр','def double(x):\n    return x * 2\nprint(double(3))','def объявляет функцию, return возвращает результат.'],
  ['Python','Строки','lower strip replace форматирование поиск','name = " Аня ".strip()\nprint(f"Привет, {name}")','Методы возвращают новые строки; f-строки подставляют значения.'],
  ['HTML','Заголовок и абзац','h1 h2 p текст','<h1>Мой сайт</h1>\n<p>Первый абзац.</p>','h1 — главный заголовок, h2 — заголовок раздела, p — абзац.'],
  ['HTML','Ссылки и изображения','a href img src alt','<a href="#plan">К плану</a>\n<img src="./photo.jpg" alt="Описание фотографии">','href задаёт цель ссылки; src — путь к существующему изображению, alt — его описание.'],
  ['HTML','Подключение файлов','link script css javascript defer','<link rel="stylesheet" href="./style.css">\n<script src="./script.js" defer></script>','Положи файлы рядом с HTML. defer откладывает выполнение скрипта до разбора документа.'],
  ['CSS','Цвета и текст','color background font-size font-family','body { color: #202738; background: #f5f7ff; font: 16px Arial, sans-serif; }','color — цвет текста, background — фон.'],
  ['CSS','Отступы и рамки','margin padding border border-radius box-sizing','.card { box-sizing: border-box; padding: 20px; margin: 10px; border: 1px solid #ddd; border-radius: 12px; }','padding внутри, margin снаружи, border — рамка.'],
  ['CSS','Flexbox','display gap wrap выравнивание','.cards { display: flex; flex-wrap: wrap; gap: 16px; align-items: center; }','Применяется к родителю и располагает его непосредственных детей.'],
  ['CSS','Адаптивность','телефон media viewport max-width','@media (max-width: 600px) {\n  .cards { flex-direction: column; }\n}','Условие действует на экранах шириной не больше 600px.'],
  ['JavaScript','let и const','переменные вычисления число строка','let count = 0;\ncount += 1;\nconst name = "Аня";','let допускает повторное присваивание; const — нет.'],
  ['JavaScript','Нажатие кнопки','событие click addEventListener обработчик','const button = document.querySelector("#plus");\nbutton.addEventListener("click", () => { console.log("Нажато"); });','Элемент должен существовать к моменту выполнения скрипта.'],
  ['JavaScript','Текст и классы','textContent classList toggle add remove','element.textContent = "Готово";\nelement.classList.toggle("done");','textContent меняет текст, toggle переключает класс; element — заранее найденный элемент.']
];
